# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 315e68a9d50e12f197440fcc83f6920cc680aff97400be04deb979618e5e95131bcc94aa712d749c271e92f6959ea0496e7fc7c635dd7ea7d2722506f7dfb318

test:
  secret_key_base: 319da3eeef2439905cadabb3dabab70e322663d831f954f97ba96c74c45d4872d5bb76481c3f65ebe19b9b00537fffd485322113045bac81a35013206b89c66c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
